### ISSUE TITLE
Dependencies not mocked

### ISSUE THREAD

**Issue by scaljeri** [Wildhoney/Mocktail#7]
Hi

I'm trying to use this library, but whatever I do, nothing gets mocked. I've setup a test repo [here](https://github.com/scaljeri/mock-es6-deps) and asked a question on [stack-overflow](http://stackoverflow.com/questions/35820440/mock-es6-dependencies-when-unit-testing). I must be doing something fundamentally wrong.

**Comment by scaljeri** [comment]
Thanks for solving this. It works now!!

**Comment by Wildhoney** [comment]
Sorry, missed this issue &mdash; glad you managed to fix it!
