### ISSUE TITLE
How to mock plain functions?

### ISSUE THREAD

**Issue by screendriver** [Wildhoney/Mocktail#8]
Assume you have
### foo.js

``` js
import { mock } from 'mocktail';

export function bar() {
  return 'i am bar';
}
```

and I **don't** want to have my stub / mock in my source file (because it's a bad design and bloats the production source code size), how can I mock `bar()` in my tests?

**Comment by nhz-io** [comment]
https://github.com/nhz-io/babel-plugin-mocktail

**Comment by Wildhoney** [comment]
Awesome work, @nhz-io!

**Comment by screendriver** [comment]
Thank you. I will try to get it running with my [jspm](http://jspm.io) / [SystemJS](https://github.com/systemjs/systemjs) setup.
